name: Playwright Tests

on:
  schedule:
    - cron: '0 */3 * * *'  # ruleazÄƒ la fiecare 3 ore
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}  # injectat global pentru toate steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build & Install Dependencies
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Compile Application
        run: mvn clean compile

      - name: Check PostgreSQL JDBC Driver
        run: mvn dependency:tree | grep postgresql

      - name: Build Package
        run: mvn clean package

      - name: Install Playwright Dependencies
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps"